//
// Created by owner on 2023/08/04.
//

#ifndef MOTORDRIVER_CONTROLLER_V4_ENCODERTYPE_HPP
#define MOTORDRIVER_CONTROLLER_V4_ENCODERTYPE_HPP

enum class EncoderType: uint8_t {
    VELOCITY,
    ANGLE
};

#endif //MOTORDRIVER_CONTROLLER_V4_ENCODERTYPE_HPP
